project:
  type: website
  output-dir: _site

website:
  title: "Shivansh Singh"
  navbar: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
  pdf:
    documentclass: article
    geometry:
      - top=20mm
      - left=20mm
      - right=20mm
      - bottom=20mm
