project:
  type: website
  output-dir: _site

website:
  title: "Shivansh Singh"
  navbar: false

format:
  html:
    theme: none
    css: style.css
    toc: false
  typst:
    papersize: us-letter
    margin:
      top: 0.45in
      bottom: 0.45in
      x: 0.75in
    font-size: 11pt
    output-file: "Resume-ShivanshSingh.pdf"
  docx:
    reference-doc: reference.docx
    output-file: "Resume-ShivanshSingh.docx"
