project:
  type: website
  output-dir: _site

website:
  title: "Shivansh Singh"
  navbar: false

format:
  html:
    theme: cosmo
    css: style.css
    toc: false
  typst:
    papersize: us-letter
    margin:
      x: 0.75in                 # Standard resume margins are usually 0.5" to 1.0"
      y: 0.75in
    font-size: 10pt
    output-file: "Resume-ShivanshSingh.pdf"