name: Render Resume

on:
  workflow_dispatch:  # adds a "Run workflow" button

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render HTML and PDF
        run: |
          quarto render index.qmd --to html,pdf

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: "Resume - Shivansh Singh.pdf"
